/*
 * generated by Xtext 2.29.0
 */
package uet.dsl.block;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlockStandaloneSetup extends BlockStandaloneSetupGenerated {

	public static void doSetup() {
		new BlockStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
