/*
 * generated by Xtext 2.29.0
 */
package uet.dsl.block;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlockRuntimeModule extends AbstractBlockRuntimeModule {
}
